### ISSUE TITLE
NPM availability

### ISSUE THREAD

**Issue by klokan** [Telerik-Verified-Plugins/Mapbox#12]
This cool plugin is not available via NPM (http://cordova.apache.org/plugins/) which makes it hard to find and harder to use (for example with PhoneGap Build).

@EddyVerbruggen Any plans to add it?

Technical details:
http://cordova.apache.org/plugins/authors.html

**Comment by EddyVerbruggen** [comment]
Good call, I'll do that!

**Comment by EddyVerbruggen** [comment]
https://www.npmjs.com/package/cordova-plugin-mapbox :+1:

**Comment by klokan** [comment]
Thank you @EddyVerbruggen

**Comment by klokan** [comment]
BTW The PhoneGap Build is successfully able to compile the iOS binary from NPM now.

Unfortunately the Android compilation fails. Are all the dependencies properly specified?
The error log: https://gist.github.com/klokan/a4cc3520d77563cc62ae#file-android-log-L211
Any hint on this issue?

**Comment by EddyVerbruggen** [comment]
Hmm, which cordova-android version are you using?

**Comment by klokan** [comment]
This error log is from the PhoneGap Build hosted service. They write now:
`PhoneGap Build (iOS / Android / Windows) cli-5.2.0 (3.9.1 / 4.1.1 / 3.8.1)`

**Comment by EddyVerbruggen** [comment]
Ah, phonegap build.. let me look at that shortly!

**Comment by klokan** [comment]
Thank you for your time and great support!

BTW We are trying to render with your wrapper for MapBox GL library our own free and open-source vector tiles for world or countries, which we have produced as part of the research project http://osm2vectortiles.org/.
It runs fine with MabBox GL JS (see http://osm2vectortiles.org/maps/), but with native instead of WebGL JavaScript it would be much better!
OSM2VectorTiles is very exciting project - it means you can host the world maps on your own server or distribute them together with the apps offline and without TOS restrictions. Mapping data are derived from OpenStreetMap database same as MapBox vector maps.

Another issue we hit with your wrapper so far is inability to specify custom map style (JSON file) for the map. In case you would have any tip for how to make this happen, your help would be greatly appreciated as well.
Details are at: https://github.com/klokantech/osm-vector-cordova/issues/2

**Comment by EddyVerbruggen** [comment]
Looking really cool!

Would you want to load that json file locally (www folder) or remotely (http)?

**Comment by klokan** [comment]
Technically both should run according the MapBox Native documentation. Local (www folder) is fine for us...

**Comment by EddyVerbruggen** [comment]
Mapbox is building their SDK with Android SDK level 23 which [doesn't seem supported yet by them](http://community.phonegap.com/nitobi/topics/error-on-cli-5-2-0-gradle-android-build-in-values-v23-values-xml). Can you check with them (in that issue or on Twitter) if/when they support v23?

**Comment by klokan** [comment]
I have asked there...

**Comment by EddyVerbruggen** [comment]
Thanks. I'd love for it to work there as well. The last Mapbox Android SDK version built with 22 is quite old so I'd rather not resort to that. And PGB should up their game by adding SDK level 23 support.

**Comment by cusspvz** [comment]
@EddyVerbruggen  Seems `1.2.0` isn't available on the npm repo.

```
josemoreira@MBP-de-JM ~/g/g/f/frontend> npm info cordova-plugin-mapbox

{ name: 'cordova-plugin-mapbox',
  description: 'Need native maps? Look no further!',
  'dist-tags': { latest: '1.1.2' },
  versions: [ '1.1.2' ],
  maintainers: [ 'eddyverbruggen <eddyverbruggen@gmail.com>' ],
  time:
   { modified: '2016-01-06T20:56:16.938Z',
     created: '2016-01-06T19:13:49.277Z',
     '1.1.1': '2016-01-06T19:13:49.277Z',
     '1.1.2': '2016-01-06T20:55:47.180Z' },
  keywords:
   [ 'Mapbox',
     'Maps',
     'Mapping',
     'Native maps',
     'ecosystem:cordova',
     'cordova-android',
     'cordova-ios' ],
  license: 'MIT',
  readmeFilename: 'README.md',
  version: '1.1.2',
  cordova_name: 'Mapbox',
  repo: 'https://github.com/Telerik-Verified-Plugins/Mapbox.git',
  issue: 'https://github.com/Telerik-Verified-Plugins/Mapbox/issues',
  platforms: [ 'android', 'ios' ],
  engines: [ { name: 'cordova', version: '>=3.5.0' } ],
  gitHead: 'a873483dca1d6bbdf9eb24ba524b554f75a5a41e',
  scripts: {},
  dist:
   { shasum: '32ecb1eeacf886851224684cc1c7fac801af9611',
     tarball: 'https://registry.npmjs.org/cordova-plugin-mapbox/-/cordova-plugin-mapbox-1.1.2.tgz' },
  directories: {} }
```
