### ISSUE TITLE
Couple of questions

### ISSUE THREAD

**Issue by liebrand** [Telerik-Verified-Plugins/Mapbox#14]
Hi there,

As per my other issue, I couldn't get this to build for Android, but I did manage to get this to work for iOS. I had a few quick questions:

- I noticed from the Mapbox.js there are only a handful of APIs available. Do you plan to add support for any of the following: setPitch, flyTo, easeTo, and being able to listen for long-press ?
- When I include this in my app, the map overlays on top of my html. Is there a way for me to float some html on top of the map? I'd like to have some floating fab buttons on top for example.

**Comment by EddyVerbruggen** [comment]
Hi,

- It's a manual job for me for both platforms so this is likely to always lag behind the JS implementation. That being said I'd love to enhance this plugin based on the needs of its users, so I'll look at those. Please let me know if there is a specific order of importance for you.
- So you have a webview and a map overlayed on top. At the moment you can't add your own button on top of that. For now the best thing to do is add a margin at the bottom/top and show your button in a menu there, but I guess you considered that approach already. If we want to overlay the map with a button (certainly possible) then it should be a bit generic so you can style it from the JS api and add behavior.. that's the hard part as everybody wants a different look and feel I guess. Any suggestions from your side in that respect?

Cheers,
Eddy
