### ISSUE TITLE
What is the performance improvement of using plug-in vs mapbox.js

### ISSUE THREAD

**Issue by jvence** [Telerik-Verified-Plugins/Mapbox#17]
Do you get a performance boost in using the plugin vs the javascript version? We've noticed that map rendering can be slow in the javascript version when you start moving around the map and zooming in and out.

**Comment by EddyVerbruggen** [comment]
If loading the tiles is causing the bottleneck then it also depends on your connection speed, but I haven't personally done a comparison. You'd best ask it at the [Mapbox GL SDK repo we're leveraging](https://github.com/mapbox/mapbox-gl-native) since they have done a comparison for sure!
