### ISSUE TITLE
[Feature] Offline map

### ISSUE THREAD

**Issue by dagatsoin** [Telerik-Verified-Plugins/Mapbox#19]
Any plans to support offline features? Coming march the 15 on ios/android

https://github.com/mapbox/mapbox-gl-native/issues/4178

**Comment by EddyVerbruggen** [comment]
We love to support all major sweet features of Mapbox so yeah! Please remind me when you see it released and want to use it.

**Comment by dagatsoin** [comment]
Roger that. If you need some help to do it I would to collaborate on the JS part if you think I have got the level for.

**Comment by EddyVerbruggen** [comment]
I don't have high standards anyway ;) Any help is truly welcome :+1:

**Comment by dagatsoin** [comment]
@EddyVerbruggen I just `git flow feature start offlineMap` so I am ready to help!
In addition to support [offline map](https://www.mapbox.com/blog/offline-mobile-maps/) I would need also to expose some useful methods like:
- [convertCoordinate:toPointToView](https://www.mapbox.com/ios-sdk/api/3.1.2/Classes/MGLMapView.html#/c:objc(cs)MGLMapView(im)convertCoordinate:toPointToView:)
- [convertPoint:toCoordinateFromView](https://www.mapbox.com/ios-sdk/api/3.1.2/Classes/MGLMapView.html#/c:objc(cs)MGLMapView(im)convertPoint:toCoordinateFromView:)
- and find a way to expose the GL matrix/camera props https://github.com/mapbox/mapbox-gl-native/issues/3668#issuecomment-191842942

My goal is to be expose essential information to sync a 2d or a 3d overlay (with three.js/pixi.js)

Do you think we can include that in the next release?

**Comment by EddyVerbruggen** [comment]
Woohoo! Excited :)

It's probably best to keep the changes (PR's) small so they're easy to merge and test for everybody.

:+1:

**Comment by dagatsoin** [comment]
Ok. This is the first time for me to collaborate on a github repo so I am not very confortable with PR's yet.
I have forked the repo and I am working on exposing `convertCoordinate`. I will try to do a PR just for this when it will work.

**Comment by dagatsoin** [comment]
I think I need help to kickstart my work. It is the first time I customize a Cordova plugin.
I try to test my method exposition but receive 
```
2016-03-25 17:55:16.203 HelloCordova[26812:753763] ERROR: Method '<null>:' not defined in Plugin 'Mapbox'
2016-03-25 17:55:16.203 HelloCordova[26812:753763] -[CDVCommandQueue executePending] [Line 142] FAILED pluginJSON = ["Mapbox1695989219","Mapbox",null,[]]

```
in CDVMapbox.h
`- (void) convertCoordinate:(CDVInvokedUrlCommand*)command;`
in CDVMapbox.m
```
- (void) convertCoordinate:(CDVInvokedUrlCommand *)command {
    NSDictionary *args = [command.arguments objectAtIndex:0];

    NSNumber *lat = [args valueForKey:@"lat"];
    NSNumber *lng = [args valueForKey:@"lng"];
    
    CGPoint screenPoint = [_mapView  convertCoordinate:CLLocationCoordinate2DMake(lat.doubleValue, lng.doubleValue)
                                         toPointToView:_mapView];

    NSArray * point = [NSArray arrayWithObjects:
                       [NSNumber numberWithFloat:screenPoint.x],
                       [NSNumber numberWithFloat:screenPoint.y],
                       nil];
    
    CDVPluginResult *pluginResult = [ CDVPluginResult
                                     resultWithStatus: CDVCommandStatus_OK
                                     messageAsArray: point
                                     ];
    [self.commandDelegate sendPluginResult:pluginResult callbackId:command.callbackId];
}
```

in Mapbox.js 
```
 convertPoint: function(options, successCallback, errorCallback){
    cordova.exec(successCallback, errorCallback, "Mapbox", "convertPoint" [options]);
  }
```

Do I miss a declaration somewhere?

**Comment by EddyVerbruggen** [comment]
That's all looking fine. Can you commit and push that code to your fork? Then I'll take a look if you like.

**Comment by dagatsoin** [comment]
I pushed it here https://github.com/dagatsoin/Mapbox/tree/feature/convertCoordinate

**Comment by EddyVerbruggen** [comment]
Take a long :eyeglasses:  at this:

<img width="195" alt="screen shot 2016-03-25 at 22 14 49" src="https://cloud.githubusercontent.com/assets/1426370/14054138/18b32e40-f2d7-11e5-870b-a982a54bc042.png">

**Comment by dagatsoin** [comment]
5s later --> OMG!!

**Comment by dagatsoin** [comment]
WIP. Close this :)

**Comment by vinibiso** [comment]
Hi guys.

I read the thread and don't know what's the state of the implementation of using the offline feature of the native Mapbox with cordova?

I didn't see anything in the docs. Furthermore, I would love to help out with anything I can.

**Comment by dagatsoin** [comment]
I will work on it next week for iOS and Android in #29 and it should already work with #22

**Comment by vinibiso** [comment]
Oh hey.

Thanks for the update. I was kind of lost.

Thanks you.
