### ISSUE TITLE
subtitle is required

### ISSUE THREAD

**Issue by frigon** [Telerik-Verified-Plugins/Mapbox#2]
I notice an unexpected issue where if the subtitle field is not present in the marker the app crashes.  Tested it in the sample app as well and seemed to be the case.

**Comment by EddyVerbruggen** [comment]
Thanks - is this on Android (only)?

**Comment by frigon** [comment]
Sorry - it should have specified.  I am testing on iOS.

**Comment by EddyVerbruggen** [comment]
Thanks - you're right, it did crash on iOS when selecting a marker without a subtitle. Fixed in 1.0.2, and now available in master.
