### ISSUE TITLE
iOS: Memory leaks when show/hide multiple times

### ISSUE THREAD

**Issue by dagatsoin** [Telerik-Verified-Plugins/Mapbox#28]
watch the memory usage in Xcode when you do show/hide. It increases 30-50mb each time.

**Comment by dagatsoin** [comment]
Could it be related to https://github.com/mapbox/mapbox-gl-native/issues/3130?

If yes, I have already compiled the latest version of MapboxGL. But I don't know what files to replace? Can you help me on this?

**Comment by dagatsoin** [comment]
More precisly, when building the latest mapbox release I miss libMapbox.a which is present in the actual cordova plugin. So what should replace libMapbox.a?

**Comment by dagatsoin** [comment]
Barely no-idea-what-I-have-done but I managed to update the iOS sdk to 3.2.0 and the memory leak is gone.
However the allocated memory space is now 130mo!! (from 30mo before the update).

**Comment by EddyVerbruggen** [comment]
Woah, that's a lot. FYI I'll be updating the SDK's to their latest releases soon.

**Comment by dagatsoin** [comment]
Ok, If you want to take a look at the iOS part, here is my branch: https://github.com/dagatsoin/Mapbox/tree/feature/placeViewBehind

**Comment by EddyVerbruggen** [comment]
Thanks, I will
