### ISSUE TITLE
Add clusters support.

### ISSUE THREAD

**Issue by Alexintosh** [Telerik-Verified-Plugins/Mapbox#30]
Example can be found here: https://www.mapbox.com/mapbox.js/example/v1.0.0/markercluster-with-mapbox-data/

**Comment by EddyVerbruggen** [comment]
That's from the JS API which we're not using. Do you have an example for the iOS and Android SDK's as well?

**Comment by Alexintosh** [comment]
Sorry for the confusion, looks like the cluster functionality are just in the legacy sdks 
https://www.mapbox.com/mapbox-ios-sdk-legacy/examples/marker-clustering/.

In the new version is just not there, but they added offline support, https://www.mapbox.com/android-sdk/offline-map/.
