### ISSUE TITLE
[Request] Support for custom map style URLs

### ISSUE THREAD

**Issue by kristfal** [Telerik-Verified-Plugins/Mapbox#38]
Hey,

I've been following the development of this plugin (really looking forward to seeing #29 and #22 landing).

Right now, the docs doesn't say anything about supporting custom map styles. It is currently only referencing the mapbox-hosted styles. 

@EddyVerbruggen is custom styles supported and undocumented, or something that needs work? Preferably, custom styles should be setable as inline JSON on map init. A good second option would be  via http:// or file:/// protocols.

**Comment by dagatsoin** [comment]
I will investigate it, has I need to put my own style too.

**Comment by dagatsoin** [comment]
In fact, it already works on the master branch, just put the url instead the classic style in the exemple. Have you got some trouble with ?

**Comment by cusspvz** [comment]
mapbox style url was already supported on Android but not on iOS.

Issue closed by #66, which implements iOS support for it.

**Comment by cusspvz** [comment]
Should be available on next patch or minor version.

**Comment by ansarikhurshid786** [comment]
I am trying to add custom style but application is stoped working and crashed
