### ISSUE TITLE
Windows cordova platform support

### ISSUE THREAD

**Issue by napcat** [Telerik-Verified-Plugins/Mapbox#39]
Does this plugin supports the windows cordova platform?

Can we aspect some love to the windows platform?

thank you

**Comment by anothar** [comment]
Hi, @napcat . This plugin relies on [Mapbox SDK](https://www.mapbox.com/developers/). However there is no SDK version for windows platform and I don't know about mapbox plans to have it. But you can use for this case regular [Mapbox GL JS](https://www.mapbox.com/mapbox-gl-js/api/). However there will be no offline maps.

**Comment by cusspvz** [comment]
Gonna close. Should be re-opened in case Mapbox GL native brings up Windows support.
