### ISSUE TITLE
title tap event handler

### ISSUE THREAD

**Issue by frigon** [Telerik-Verified-Plugins/Mapbox#4]
I want to move from a pin on the map to a detail page about that item.  Ideally the flow would be user taps on the pin and sees the title/subtitle combination.  then taps it the title/subtitle element to go to the detail page.  I don't see any event handler that is available for the doubletap and/or the title/subtitle element.

**Comment by EddyVerbruggen** [comment]
On iOS you can add a JS handler which is called when a marker is selected, IIRC it fires immediately, not when tapping the title. I'm not sure Mapbox supports this on Android, but if you let me know this is useful then I can ask the Mapbox guys if it's something we can do on Android as well.

Here's the code: https://github.com/Telerik-Verified-Plugins/Mapbox/blob/master/demo/index.html#L114-L117

**Comment by frigon** [comment]
Yes I have the event handler for the marker click event - that works fine.  i'm trying to do the common progressive disclosure tactic of show all the markers... tap to get the name of each marker then either tap again or tap the title and then to go to a detail page.

I'm trying on ios 9

**Comment by EddyVerbruggen** [comment]
Seems like a useful case to support - I've done it for Android now, still looking for a way on iOS.

**Comment by frigon** [comment]
For this to work this would probably need to obtain some kind of ID for the item tapped on so that you can determine which item details to display. See the other "metadata" issue. 

Thanks love this plugin.

**Comment by EddyVerbruggen** [comment]
Hey @frigon I found a way to add a custom (i) icon on the marker callout for iOS. It will only be shown when the marker selection callback has been set. Now the callback is fired when the icon is pressed (iOS) or the entire callout is pressed (Android).

How that's what you need.

Available in 1.1.0.
