### ISSUE TITLE
Using plugin with typescript

### ISSUE THREAD

**Issue by napcat** [Telerik-Verified-Plugins/Mapbox#40]
I was trying to use this plugin in a typescript project. I installed the plugin and tried to call the Mapbox.show method, but got an error:

`Cannot find name "Mapbox" `

The app does not compile. I searched for the definitions file, but found none. 

Is there any other way to make this run on a typescript project?

**Comment by EddyVerbruggen** [comment]
You can use any standard JS lib with TS so I don't get the point. If you want to contribure a `.d.ts` file that would be great of course.

**Comment by peridotlib15** [comment]
I am facing the same issue
I am developing an app using Ionic 2 and typescript.
I want to use this plugin but get the same issue.
Do you have any solution?

**Comment by anothar** [comment]
Hi, @peridotlib15 . Simplest solution is to declare Mapbox variable in .ts file before module or namespace declaration. Like below.

> declare var Mapbox: any;

**Comment by anothar** [comment]
Wow, actually I implemented typescript definition file. It's in attachment - rename it to mapbox.d.ts
[mapbox.txt](https://github.com/Telerik-Verified-Plugins/Mapbox/files/387725/mapbox.txt)
.

**Comment by EddyVerbruggen** [comment]
Can you be bothered to send a PR perhaps? Thanks for sharing anyway!

**Comment by anothar** [comment]
I'll do PR. But first of all I'll add all functions to TypeScript definition file. Currently there is only part of them.

**Comment by cusspvz** [comment]
@anothar do you mind to add it on a different PR? It seems that you have lots of contributions, which is awesome!! But for faster PR landing, i would recommend you to divide them on PRs/branches.

Inspite of it, I'm gonna try to cherry pick your commit into a new PR so we can close this issue ASAP.

**Comment by cusspvz** [comment]
@anothar done it.

**Comment by vbudilov** [comment]
@cusspvz -- Hello! Any idea when 1.3.0 is going to be released? Trying to integrate this plugin with Ionic3 but it's not as clear-cut as I thought. 

Thanks...

**Comment by ansarikhurshid786** [comment]
@vbudilov is it working with ionic 3?
