### ISSUE TITLE
Multiple maps open

### ISSUE THREAD

**Issue by frigon** [Telerik-Verified-Plugins/Mapbox#44]
I've verified this issue with the sample app as well. I've realized that if you call Mapbox.show before closing an existing map multiple maps get opened and you lose the ability to close the prior map. So you're left with a map that can't be removed.

I've also tried to chain a hide call with an show call in the callback but it seems the callback in hide doesn't get called.

I'd recommend at least some kinda of function or property that lets you check if the originally map is already open.

**Comment by anothar** [comment]
Hi @frigon  I've fixed hide callback in [my fork](https://github.com/anothar/Mapbox/tree/features_image_marker)
