### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by peridotlib15** [Telerik-Verified-Plugins/Mapbox#47]
Hello
I am developing an application in Ionic 2 with Typescript.
I installed your plugin but it says cannot find find plugin.
Is there a way to use the plugin with Typescript?

**Comment by anothar** [comment]
Linked to [this issue](https://github.com/Telerik-Verified-Plugins/Mapbox/issues/40).

**Comment by cusspvz** [comment]
Will be available on the next release. PR #64
