### ISSUE TITLE
Android build for Cordova 4.0 fails in AppBuilder

### ISSUE THREAD

**Issue by Mike4o** [Telerik-Verified-Plugins/Mapbox#5]
Here is the exact error:
[2015-10-13 15:50:37.070] Exception: Server exception: Project "PT977462.tmp.proj" (default targets):
	android Build Tooling revision 2015.09.30.2r
	Warning: Note: Some input files use or override a deprecated API.
	Warning: Note: Recompile with -Xlint:deprecation for details.
	Warning: Note: Some input files use or override a deprecated API.
	Warning: Note: Recompile with -Xlint:deprecation for details.
	Warning: FAILURE:
	Warning: Build failed with an exception.
	Warning: * What went wrong:
Execution failed for task ':mergeArmv7DebugResources'.
> /tmp/builds/BQbFw7rXD8QhmYkFEa/app/res/values/mapboxstrings.xml: Error: Found item String/mapbox_accesstoken more than one time

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
	Warning: /tmp/builds/BQbFw7rXD8QhmYkFEa/app/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error code 1 for command: /tmp/builds/BQbFw7rXD8QhmYkFEa/app/gradlew with args: cdvBuildDebug,-b,/tmp/builds/BQbFw7rXD8QhmYkFEa/app/build.gradle,-Dorg.gradle.daemon=true,-PcdvBuildArch=armv7,-PcdvBuildMultipleApks=true
	Error: /tmp/builds/BQbFw7rXD8QhmYkFEa/app/res/values/mapboxstrings.xml: Error: Found item String/mapbox_accesstoken more than one time
	Error: Build failed during execution
	Error: 'Build failed with error code 8'
Done building project "PT977462.tmp.proj" -- FAILED.

You can directly reproduce it with the sample app from https://plugins.telerik.com/cordova/plugin/mapbox. Most likely it is due to the plugin variable setup.

**Comment by EddyVerbruggen** [comment]
Oh nice - this worked a week ago!

**Comment by EddyVerbruggen** [comment]
Adding the plugin as a manual upload doesn't have the same problem: builds correctly. That makes fixing this only harder though.

**Comment by EddyVerbruggen** [comment]
Fixed in 1.0.2
