### ISSUE TITLE
No css file

### ISSUE THREAD

**Issue by iconbloom** [Telerik-Verified-Plugins/Mapbox#54]
No index.css in the file and map not appear.

**Comment by EddyVerbruggen** [comment]
?

**Comment by iconbloom** [comment]
I'm  not able to implement. I'm using ionic framework to test it.

**Comment by cusspvz** [comment]
This plugin uses native MapBox GL, which means it doesn't load under the WebView.

Please do read the Usage on the README, re-open in case you have an issue implementing it. Thanks.

Closing this up.
