### ISSUE TITLE
Callback when map moves or zoom changes

### ISSUE THREAD

**Issue by otmezger** [Telerik-Verified-Plugins/Mapbox#56]
Hi, 

I'm coming from leaflet and my app uses the **[dragstart](http://leafletjs.com/reference.html#map-dragstart)** callback for some functionality, specially for getting data from the server once the user moves the map. I also use a zoom callback for the same purpose. 

Does this plugin provides such functionality? I haven't seen it in the documentation. 

thanks of any advice

**Comment by cusspvz** [comment]
Isn't provided on docs yet, iOS support for region change callbacks was added at #24, and I've finished the Android implementation at #61 .

You can check the API [here](https://github.com/Telerik-Verified-Plugins/Mapbox/blob/6636bce4e748cc81ec3367c5f9fb891e321a76a4/demo/index.html#L136-L146) until we have them on the docs.
