### ISSUE TITLE
Bind the map to a html element

### ISSUE THREAD

**Issue by otmezger** [Telerik-Verified-Plugins/Mapbox#57]
I have some animations on my app, for example a sliding menu. my current map (pure js, with leaflet) moves nicely right and left as the menu opens and closes because it is bound to a html element. 

is it possible to bind the map produced by this plugin to a html element?

**Comment by cusspvz** [comment]
discussion: https://github.com/Telerik-Verified-Plugins/Mapbox/pull/29

**Comment by cusspvz** [comment]
found out to be duplicated of #37
