### ISSUE TITLE
about marker clustering

### ISSUE THREAD

**Issue by pirodex** [Telerik-Verified-Plugins/Mapbox#6]
Hi,

Is Mapbox support marker clustering?

**Comment by jvence** [comment]
Good question

**Comment by EddyVerbruggen** [comment]
Not that I know, but you're better off [searching their Github](https://github.com/mapbox/mapbox-gl-native/search?q=clustering&type=Issues&utf8=%E2%9C%93) and/or checking the API's. I'm interested to learn if it's possible (now or in the future)!
