### ISSUE TITLE
Support for Mapbox Style Specification

### ISSUE THREAD

**Issue by jczaplew** [Telerik-Verified-Plugins/Mapbox#73]
Are there any plans to support the [Mapbox Style Specification](https://www.mapbox.com/mapbox-gl-style-spec/), which would allow for the addition of custom tile layers and greater control over styles?

**Comment by cusspvz** [comment]
Android already supported Mapbox Style Specification. The iOS support was added on the PR #66 .

**Comment by jczaplew** [comment]
Thanks!
