### ISSUE TITLE
Adding JS event on pin click

### ISSUE THREAD

**Issue by kgeoir** [Telerik-Verified-Plugins/Mapbox#81]
in order to improve UX, we need an event to be triggered when the user click on a pin. How could we do that? Is someone able to help?

**Comment by dagatsoin** [comment]
Is this you are looking for http://plugins.telerik.com/cordova/plugin/mapbox ? (near the bottom of the page)

**Comment by kgeoir** [comment]
Looks interesting, I will check and let you know!
Tks!
