### ISSUE TITLE
addMarkerCallback does not show clickable button in popup on Android 5.1.0

### ISSUE THREAD

**Issue by yipcma** [Telerik-Verified-Plugins/Mapbox#83]

**Comment by yipcma** [comment]
PS: clicking bubble itself would trigger callback. OP is out of curiosity, not a bug report.

**Comment by cusspvz** [comment]
Can you please check again? If i am not wrong, the callback is attached to the popup whenever there is info, but if there isnt it will be attached to the marker itself.

**Comment by cusspvz** [comment]
Closing until we have response from OP
