### ISSUE TITLE
How to use with ionic 3

### ISSUE THREAD

**Issue by ansarikhurshid786** [Telerik-Verified-Plugins/Mapbox#91]
Hi, 
I am developing hybrid application with ionic 3 and angular 4. Can anyone help me how to use it with ionic 3?

**Comment by ansarikhurshid786** [comment]
I got solution. 

I declare a variable globally then:  
declare let Mapbox: any;

**Comment by risinghero** [comment]
Nice. Actually there is typescript definition in plugin directory - search by name: mapbox.d.ts. You can just add reference to it. And you also will get declarations for all methods.

**Comment by ansarikhurshid786** [comment]
ok Thanks
