### ISSUE TITLE
How to add element over map

### ISSUE THREAD

**Issue by ansarikhurshid786** [Telerik-Verified-Plugins/Mapbox#96]
Hi, 
I want to add current location button and other some user button. How can i add it properly which support android and ios. because i can't see where this map is rendering.

**Comment by risinghero** [comment]
Hi @ansarikhurshid786 map is rendered inside ios and android code. You can try to fork plugin and add yourself into ios and android code required button.

**Comment by ansarikhurshid786** [comment]
I want to use it because it give best user experience. Presently I am using mailbox-gl-js which is really bad user experience in ionic 3 android and iOS application.

**Comment by ansarikhurshid786** [comment]
I don't have that much experience to fork and add my own. can you help me add button over map and how to load map in specific html element id.

**Comment by risinghero** [comment]
> how to load map in specific html element id
I can't since it requires lots of work and time. You can look at @dagatsoin branch. In my experience mapbox-gl-js had some problems with old browsers. Maybe it's better to use just leaflet+mapbox tiles

**Comment by ansarikhurshid786** [comment]
Yes, mailbox-gl-js not good performance in mobile application. Should I use this plugin or not

**Comment by risinghero** [comment]
> Should I use this plugin or not

Well it's up to you to decide. But I don't think that adding elements over map will be ready soon.
Regarding mapbox-gl-js instead of it just use leaflet+mapbox tiles it won't require many changes in your code and you will get good performance. The only problem-it won't work offline,

**Comment by ansarikhurshid786** [comment]
ok thanks. just tell me leaflet + mapbox will support 3d also. if you have link for leaflet + mapbox can you please send me.

**Comment by risinghero** [comment]
Not it won't. Leaflet just for 2D.

**Comment by ansarikhurshid786** [comment]
Oh but I want 3d also. Anyway thanks a lot for giving me your valuable time.

**Comment by ansarikhurshid786** [comment]
@risinghero can you help me to add fab button over map?

**Comment by ansarikhurshid786** [comment]
@risinghero how to use leaflet+mapbox? can you give me any reference please

**Comment by risinghero** [comment]
Hi, @ansarikhurshid786 . Here is [example](https://leafletjs.com/examples/quick-start/)
But I think that you can add button into this plugin by yourself - just fork it, add button into android and iOS code and add events

**Comment by ansarikhurshid786** [comment]
Ok thanks I will check. You mean leflet right. I think leflet base on mapbox, am I right?

**Comment by ansarikhurshid786** [comment]
Yes, Leaflet is much faster than mapbox gl js. Thanks a lot @risinghero
