### ISSUE TITLE
No support and maintainance

### ISSUE THREAD

**Issue by ansarikhurshid786** [Telerik-Verified-Plugins/Mapbox#97]
Every mobile framework has mapbox support like react-native, google flutter, xamarin but why not cordova or ionic framework. I am lot of performance issue with mapbox gl js.

**Comment by EddyVerbruggen** [comment]
Hi! Are you offering to maintain this plugin?

**Comment by ansarikhurshid786** [comment]
No. I don't have that much experience.

**Comment by ansarikhurshid786** [comment]
I am using mapbox gl js in ionic 3 framework but facing lot of performance issue and neither official nor any other support for cordova or ionic framework which work properly.

**Comment by ansarikhurshid786** [comment]
I tried to use this plugin but has lot of issue.

**Comment by EddyVerbruggen** [comment]
Yeah, I can imagine. This plugin depends on community members for maintenance - Ionic doesn't support plugins they didn't create themselves AFAIK.

**Comment by ansarikhurshid786** [comment]
but also has issue with core cordova

**Comment by EddyVerbruggen** [comment]
Same - Cordova doesn't support plugins they didn't create themselves - it's all up to the community.

**Comment by ansarikhurshid786** [comment]
@EddyVerbruggen you have developed and maintaining for nativescript. why not also support for cordova framework. it will help lot of people.

**Comment by EddyVerbruggen** [comment]
My workday only has 12 hours, sorry.
